name: Project Create Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  pre-project-create-release:
    uses: ./.github/workflows/java-maven-package.yml
    secrets: inherit

  project-create-release:
    needs: pre-project-create-release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --notes "" --draft

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} build/*.zip
